
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: bc12a9f
_src_path: /home/musicvivireal/code/github.com/codingvivi/42-c_template
build_system: makefile
copy_build_to_root: true
flat_repo: true
project_name: push_swap
project_type: ConsoleApp
submit_makefile: true
use_clang_format: true
use_clangd: true
use_just: true
use_libft: true
